config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}#, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :users, except: :create do
    member do
      put :update_name
      put :lock
      put :unlock
    end
    collection do
     get :stats_by_domain
    #   get :stats_by_year
    #   get :stats_by_current_week
    #   get :stats_by_year_by_month
    #   get :stats_by_year_by_week
    end
  end
  post 'create_user' => 'users#create', as: :create_user
  resources :user_settings

  match 'api(/:id)' => 'api#options', via: [:options]
  resources :api do
    collection do
      get :discover
      get :list
      get :form
      get :form_annotations
      get :domain
      get :thesaurus_concept
      get :bc_property
    end
  end
  namespace :api do
    namespace :v2 do
      resources :thesauri, only: [:show]
      resources :thesaurus_concepts, only: [:index, :show] do
        member do
          get :parent
          get :child
        end
      end
      resources :iso_managed, only: [:index]
      resources :biomedical_concepts, only: [] do
        member do
          get :domains
        end
      end
      resources :sdtm_user_domains, only: [:show]
      resources :sdtm_ig_domains, only: [:show] do
        member do
          get :clones
        end
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
  resources :iso_namespaces, only: [:index, :new, :create, :destroy]
  resources :iso_registration_authorities, only: [:index, :new, :create, :destroy]
  resources :iso_scoped_identifiers, only: [:update]
  resources :iso_scoped_identifiers_v2, only: [:update]
  resources :iso_registration_states, only: [:update] do
    collection do
      get :current
    end
  end
  resources :iso_concept, only: [:show] do
    collection do
      get :graph
      get :graph_links
      get :impact
      get :impact_start
      get :impact_next
      get :changes
    end
    member do
      get :tags
      put :add_tag
      put :remove_tag
      get :edit_tags
      get :tags_full
      get :change_notes
      get :change_instructions
      get :indicators
      post :change_note, action: :add_change_note
    end
  end
  namespace :annotations do
    resources :change_notes, only: [:update, :destroy]
    resources :change_instructions, only: [:create, :edit, :update, :destroy] do
      member do
        get :show
        put :add_references
        put :remove_reference
      end
    end
  end
  resources :iso_managed do
    collection do
      get :status
      get :find_by_tag
      get :tags
      get :graph
      get :graph_links
      get :impact
      get :impact_start
      get :impact_next
      get :changes
      get :comments
    end
    member do
      get :branches
      get :export
    end
  end
  resources :iso_managed_v2, only: [] do
    member do
      get :status
      get :impact
      get :make_current
      post :update_status
      put :update_semantic_version
      get :list_change_notes
      get :list_change_notes_data
      get :export_change_notes_csv
    end
    collection do
      get :find_by_tag
    end
  end
  resources :iso_registration_states_v2, only: [] do
    member do
      put :update
    end
  end
  resources :dashboard, only: [:index] do
    collection do
      get :view
      get :database
      get :admin
    end
  end
  resources :iso_concept_systems, only: [:index, :show, :destroy] do
    member do
      post :add
    end
  end
  namespace :iso_concept_systems do
    resources :nodes, only: [:destroy, :update] do
      member do
        post :add
      end
    end
  end
  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
      get :stats_by_domain
      get :stats_by_year
      get :stats_by_current_week
      get :stats_by_year_by_month
      get :stats_by_year_by_week
    end
  end
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end
  resources :ad_hoc_reports, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :run_start
      get :run_progress
      get :run_results
      get :results
      get :export_csv
    end
  end

  # Thesauri
  namespace :thesauri do
    resources :managed_concepts, only: [:index, :show, :edit, :update, :create, :destroy] do
      collection do
        get :history
        get :set_with_indicators
      end
      member do
        get :edit_extension
        get :edit_subset
        get :find_subsets
        get :children
        post :add_child
        post :add_children_synonyms
        post :create_extension
        post :create_subset
        get :show_data
        get :changes
        get :changes_data
        get :changes_report
        get :differences
        get :synonym_links
        get :preferred_term_links
        get :change_instruction_links
        post :extensions, action: :add_extensions
        # delete :extensions, action: :destroy_extensions
        get :is_extended
        get :is_extension
        get :export_csv
        get :changes_summary
        get :changes_summary_data
        get :changes_summary_data_impact
        get :impact
        get :differences_summary
        patch :update_properties
        get :upgrade_data
        put :upgrade
        post :add_rank
        delete :remove_rank
        put :update_rank
        get :get_ranked_children
      end
    end
    resources :unmanaged_concepts, only: [:show, :edit, :update, :destroy] do
      member do
        get :show_data
        get :changes
        get :changes_data
        get :differences
        get :synonym_links
        get :preferred_term_links
        get :change_instruction_links
        patch :update_properties
      end
    end
    resources :subsets, only: [] do
      member do
        post :add
        delete :remove
        delete :remove_all
        put :move_after
        get :list_children
      end
    end
  end

  resources :thesauri, only: [:index, :show, :create, :edit, :destroy] do
    collection do
      get :index_owned
      get :history
      post :extension
      get :search_current
      get :search_multiple
    end
    member do
      post :clone
      get :children
      get :children_with_indicators
      post :add_child
      get :changes
      get :changes_data
      get :changes_report
      get :changes_impact
      get :export_csv
      get :submission
      get :submission_data
      get :submission_report
      get :search
      get :export_csv
      post :add_subset
      get :release_select
      put :reference, action: :set_reference
      get :reference, action: :get_reference
      post :select_children
      put :deselect_children
      put :deselect_all_children
      put :change_child_version
      get :compare
      get :compare_data
      get :compare_csv
      get :upgrade
    end
  end

  # resources :thesaurus_concepts, :only => [:update, :show, :destroy, :edit] do
  #   collection do
  #     get :children
  #     post :add_child
  #   end
  #   member do
  #     get :cross_reference_start
  #     get :cross_reference_details
  #   end
  # end

  resources :uploads, :only => [:index, :create] do
    collection do
      delete :destroy_multiple
      delete :destroy_all
    end
  end

  # Imports
  namespace :imports do
    # resources :adam_models, :only => [:new, :create]
    # resources :adam_igs, :only => [:new, :create]
    resources :cdisc_terms, :only => [:new, :create]
    resources :change_instructions, :only => [:new, :create]
    resources :crfs, :only => [:new, :create] do
      collection do
        get :items
      end
    end
    resources :sponsor_term_format_two, :only => [:new, :create]
  end
  resources :imports, :only => [:index, :show, :destroy] do # Make sure this is after the namespace to avoid the :index/:show clash
    collection do
      get :list
      delete :destroy_multiple
    end
  end

  # Exports
  resources :exports, :only => [:index] do
    collection do
      get :terminologies
      get :biomedical_concepts
      get :forms
      get :start
      get :download
    end
  end

  # CDISC Terminology
  resources :cdisc_terms, :only => [:index] do
    collection do
      get :history
    end
    member do
    end
  end

  # BCs
  resources :biomedical_concept_templates do
    collection do
      get :history
      get :list
      get :all
    end
  end
  namespace :biomedical_concepts do
    resources :items
    resources :datatypes
    resources :properties do
      member do
        post 'term', to: 'properties#add', as: :add
        delete 'term', to: 'properties#remove', as: :remove
      end
    end
    resources :property_values
  end
  resources :biomedical_concepts do
    member do
      get :export_json
      get :export_ttl
      get :clone
      get :upgrade
      get :show_full
      get :edit_lock
    end
    collection do
      get :editable
      get :history
      post :clone_create
      get :list
      get :edit_multiple
    end
  end
  resources :forms do
    collection do
      get :history
      get :view
      get :placeholder_new
      post :placeholder_create
      get :acrf
      get :crf
      get :markdown
      get :clone
      post :clone_create
      get :branch
      post :branch_create
      get :export_json
      get :export_ttl
      get :export_odm
    end
  end
  namespace :forms do
    resources :groups
    resources :items, :only => [:show]
  end
  resources :backgrounds, :only => [:index, :destroy] do
    collection do
      delete :destroy_multiple
    end
  end
  resources :sdtm_models do
    collection do
      get :history
      get :import
      post :create
    end
    member do
      get :export_json
      get :export_ttl
    end
  end
  namespace :sdtm_models do
    resources :variables
  end

app/views/shared/headers/_header_by_type.html.erb
<%
  case type
    when "Thesaurus"
      header_path = "shared/headers/header_managed_item"
      locals = {item: @item, badge: "icon-terminology", with_tags: with_tags}
    when "Thesaurus::ManagedConcept"
      header_path = "shared/headers/header_codelist"
      @item.synonyms_and_preferred_terms
      locals = {item: @item, badge: "CL", with_tags: with_tags}
    when "Thesaurus::UnmanagedConcept"
      header_path = "shared/headers/header_unmanaged_item"
      @item.synonyms_and_preferred_terms
      locals = {item: @item, badge: "CI", with_tags: with_tags}
  end %>

<%= render layout: header_path, :locals => locals do %>
  <% yield %>
<% end %>

app/views/shared/headers/_header_codelist.html.erb
<%= stylesheet_link_tag 'shared/layouts/header_card' %>

<div id="imh_header" class="col-md-12 card">
  <div class="card-content">
    <div class="h-outside-wrap">
      <div class="h-inner-wrap centered">
        <span class="circular-badge big <%= item_accent_color item.owner_short_name %> text-white">
          <%= badge %>
        </span>
        <span class="text-centered text-normal text-light" style="margin-top: 5px;"><%= item.scoped_identifier %></span>
        <div>
          <% if item.extensible %>
            <span class="icon-extend text-secondary-clr"></span> <span class="font-light text-tiny">Extensible</span>
          <% else %>
            <span class="icon-extend-disabled text-accent-2"></span> <span class="font-light text-tiny">Not extensible</span>
          <% end %>
        </div>
      </div>
      <div class="h-inner-wrap mid">
        <div class="text-large"> <%= item.notation %> </div>
        <div class="label-w-margin">Preferred term: <span class="font-light"> <%= item.preferred_term.label %> </span></div>
        <div class="label-w-margin">
            <%= render partial: "shared/bg_labels_inline", :locals => {:name => "Synonym(s)", :items => item.synonym.map{|x| x.label} } %>
        </div>
        <div class="definition-label label-w-margin">
          Definition: <span class="font-light"><%= item.definition %> </span>
        </div>
        <% if (local_assigns.fetch :with_tags, true) %>
          <%= render layout: "shared/show_more", :locals => {:size => "tiny"} do %>
            <%= render partial: "shared/bg_labels_inline", :locals => {:name => "Tags", :items => item.filtered_tag_labels(context)} %>
          <% end %>
        <% end %>
      </div>
      <div class="h-inner-wrap indicators-wrap">
        <%= yield %>
        <%= render partial: "shared/headers/indicators", locals: {id: item.id, wrap_el: ".h-inner-wrap.indicators-wrap"} %>
      </div>
    </div>
  </div>
</div>
<%= javascript_tag 'colorCodeTagsOutline(".show-more-wrap", ".tags.bg-label");' %>

app/views/shared/headers/_header_generic.html.erb
<%= stylesheet_link_tag 'shared/layouts/header_card', media: 'all' %>

<div class="col-md-12 card">
  <div class="card-content">
    <div class="h-outside-wrap">
      <div class="h-inner-wrap mid">
        <% if !header_title.empty? %>
          <div class="h-inner-wrap text-small header-title"><%= header_title %></div>
        <% end %>
        <div class="h-inner-wrap rb" style="flex-direction: row;">
          <div class="h-inner-wrap">
            <span class="circular-badge big bg-accent-1 text-white">
              <%= if badge.include? "icon" then ("<span class='"+ badge +"'></span>").html_safe else badge end %>
            </span>
          </div>
          <div class="h-inner-wrap mid">
            <div class="text-large"> <%= main_text %> </div>
            <div class="text-small font-light">
              <% if sub_texts.is_a? Array %>
                <% sub_texts.each_with_index do |item, index| %>
                  <span class="font-regular"> <%= item[:title] %>: </span><%= item[:value] %>
                  <%= "&nbsp;|&nbsp;".html_safe if (index != sub_texts.length - 1) %>
                <% end %>
              <% else %>
                <span> <%= sub_texts %> </span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="h-inner-wrap">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/shared/headers/_header_item_simple.html.erb
<%= stylesheet_link_tag 'shared/layouts/header_card', media: 'all' %>

<div class="col-md-12 card">
  <div class="card-content">
    <div class="h-outside-wrap">
      <div class="h-inner-wrap mid">
        <div class="h-inner-wrap text-small header-title"><%= header_title %></div>
        <div class="h-inner-wrap rb" style="flex-direction: row;">
          <div class="h-inner-wrap">
            <span class="circular-badge big <%= item_accent_color item.owner_short_name %> text-white">
              <%= if badge.include? "icon" then ("<span class='"+ badge +"'></span>").html_safe else badge end %>
            </span>
          </div>
          <div class="h-inner-wrap mid">
            <div class="text-large"> <%= item.label %> </div>
            <div class="text-small font-light"> Owner: <%= item.owner_short_name %> &nbsp; | &nbsp; Identifier: <%= item.scoped_identifier %></div>
          </div>
        </div>
      </div>
      <div class="h-inner-wrap">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/shared/headers/_header_managed_item.html.erb
<%= stylesheet_link_tag 'shared/layouts/header_card', media: 'all' %>

<div id="imh_header" class="col-md-12 card">
  <div class="card-content">
    <div class="h-outside-wrap">
      <div class="h-inner-wrap">
        <span class="circular-badge big <%= item_accent_color item.owner_short_name %> text-white">
          <%= if badge.include? "icon" then ("<span class='"+ badge +"'></span>").html_safe else badge end %>
        </span>
      </div>
      <div class="h-inner-wrap mid">
        <div class="text-small font-light"> Owner: <%= item.owner_short_name %> &nbsp; | &nbsp; Identifier: <%= item.scoped_identifier %></div>
        <div class="text-large"> <%= item.label %> </div>
        <div class="font-light">
            <%= render partial: "shared/headers/icon_tooltip", :locals => {:title => item.registration_status, :icon => "icon-info-circle", :description => "Status"} %>
            <%= render partial: "shared/headers/icon_tooltip", :locals => {:title => item.semantic_version, :icon => "icon-version-circle", :description => "Version"} %>
            <%= render partial: "shared/headers/icon_tooltip", :locals => {:title => item.version_label, :icon => "icon-tag-circle", :description => "Version label"} %>
        </div>
        <% if (local_assigns.fetch :with_tags, true) %>
          <%= render layout: "shared/show_more", :locals => {:size => "tiny"} do %>
            <%= render partial: "shared/bg_labels_inline", :locals => {:name => "Tags", :items => item.tag_labels} %>
          <% end %>
        <% end %>
      </div>
      <div class="h-inner-wrap">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
<%= javascript_tag 'colorCodeTagsOutline(".show-more-wrap", ".tags.bg-label");' %>

app/views/shared/headers/_header_minimal.html.erb
<%= stylesheet_link_tag 'shared/layouts/header_card', media: 'all' %>

<div class="col-md-12 card">
  <div class="card-content">
    <div class="h-outside-wrap">
        <div class="h-inner-wrap mid">
          <div class="h-inner-wrap rb" style="flex-direction: row;">
            <div class="h-inner-wrap">
              <span class="text-xxxlarge <%= badge %> <%= item_accent_text_color(local_assigns.fetch :owner, "") %>"></span>
            </div>
          <div class="h-inner-wrap mid">
            <div class="text-large text-link"> <%= main_text %> </div>
            <div class="text-small font-light">
                <span> <%= sub_text %> </span>
            </div>
          </div>
        </div>
      </div>
      <div class="h-inner-wrap">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/shared/headers/_header_unmanaged_item.html.erb
<%= stylesheet_link_tag 'shared/layouts/header_card', media: 'all' %>

<div class="col-md-12 card">
  <div class="card-content">
    <div class="h-outside-wrap">
      <div class="h-inner-wrap centered">
        <span class="circular-badge big <%= item_accent_color item.uri.to_s %> text-white"><%= badge %></span>
        <span class="text-centered text-normal text-light" style="margin-top: 5px;"><%= item.identifier %></span>
      </div>
      <div class="h-inner-wrap mid">
        <div class="text-large"> <%= item.notation %> </div>
        <div class="label-w-margin">Preferred term: <span class="font-light"> <%= item.preferred_term.label %> </span></div>
        <div class="label-w-margin">
          <%= render partial: "shared/bg_labels_inline", :locals => {:name => "Synonym(s)", :items => item.synonym.map{|x| x.label} } %>
        </div>
        <div class="definition-label label-w-margin">
          Definition: <span class="font-light"><%= item.definition %> </span>
        </div>
        <% if (local_assigns.fetch :with_tags, true) %>
          <%= render layout: "shared/show_more", :locals => {:size => "tiny"} do %>
            <%= render partial: "shared/bg_labels_inline", :locals => {:name => "Tags", :items => item.filtered_tag_labels(context)} %>
          <% end %>
        <% end %>
      </div>
      <div class="h-inner-wrap indicators-wrap">
        <%= yield %>
        <%= render partial: "shared/headers/indicators", locals: {id: item.id, wrap_el: ".h-inner-wrap.indicators-wrap"} %>
      </div>
    </div>
  </div>
</div>
<%= javascript_tag 'colorCodeTagsOutline(".show-more-wrap", ".tags.bg-label");' %>

app/views/shared/headers/_icon_tooltip.html.erb
 <span class="<%= icon %> ttip ttip-ico"><span class="ttip-text shadow-small text-medium text-small"><%= description %></span></span><span class="icotext"><%= title %></span>

app/views/shared/headers/_indicators.html.erb
<%= stylesheet_link_tag 'shared/processing/shiny_processing' %>

<div class="indicators"></div>
<%= javascript_tag "loadItemIndicators('#{indicators_iso_concept_path(id)}', '#{wrap_el} .indicators');" %>