config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}#, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :users, except: :create do
    member do
      put :update_name
      put :lock
      put :unlock
    end
    collection do
     get :stats_by_domain
    #   get :stats_by_year
    #   get :stats_by_current_week
    #   get :stats_by_year_by_month
    #   get :stats_by_year_by_week
    end
  end
  post 'create_user' => 'users#create', as: :create_user
  resources :user_settings

  match 'api(/:id)' => 'api#options', via: [:options]
  resources :api do
    collection do
      get :discover
      get :list
      get :form
      get :form_annotations
      get :domain
      get :thesaurus_concept
      get :bc_property
    end
  end
  namespace :api do
    namespace :v2 do
      resources :thesauri, only: [:show]
      resources :thesaurus_concepts, only: [:index, :show] do
        member do
          get :parent
          get :child
        end
      end
      resources :iso_managed, only: [:index]
      resources :biomedical_concepts, only: [] do
        member do
          get :domains
        end
      end
      resources :sdtm_user_domains, only: [:show]
      resources :sdtm_ig_domains, only: [:show] do
        member do
          get :clones
        end
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
  resources :iso_namespaces, only: [:index, :new, :create, :destroy]
  resources :iso_registration_authorities, only: [:index, :new, :create, :destroy]
  resources :iso_scoped_identifiers, only: [:update]
  resources :iso_scoped_identifiers_v2, only: [:update]
  resources :iso_registration_states, only: [:update] do
    collection do
      get :current
    end
  end
  resources :iso_concept, only: [:show] do
    collection do
      get :graph
      get :graph_links
      get :impact
      get :impact_start
      get :impact_next
      get :changes
    end
    member do
      get :tags
      put :add_tag
      put :remove_tag
      get :edit_tags
      get :tags_full
      get :change_notes
      get :change_instructions
      get :indicators
      post :change_note, action: :add_change_note
    end
  end
  namespace :annotations do
    resources :change_notes, only: [:update, :destroy]
    resources :change_instructions, only: [:create, :edit, :update, :destroy] do
      member do
        get :show
        put :add_references
        put :remove_reference
      end
    end
  end
  resources :iso_managed do
    collection do
      get :status
      get :find_by_tag
      get :tags
      get :graph
      get :graph_links
      get :impact
      get :impact_start
      get :impact_next
      get :changes
      get :comments
    end
    member do
      get :branches
      get :export
    end
  end
  resources :iso_managed_v2, only: [] do
    member do
      get :status
      get :impact
      get :make_current
      post :update_status
      put :update_semantic_version
      get :list_change_notes
      get :list_change_notes_data
      get :export_change_notes_csv
    end
    collection do
      get :find_by_tag
    end
  end
  resources :iso_registration_states_v2, only: [] do
    member do
      put :update
    end
  end
  resources :dashboard, only: [:index] do
    collection do
      get :view
      get :database
      get :admin
    end
  end
  resources :iso_concept_systems, only: [:index, :show, :destroy] do
    member do
      post :add
    end
  end
  namespace :iso_concept_systems do
    resources :nodes, only: [:destroy, :update] do
      member do
        post :add
      end
    end
  end
  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
      get :stats_by_domain
      get :stats_by_year
      get :stats_by_current_week
      get :stats_by_year_by_month
      get :stats_by_year_by_week
    end
  end
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end
  resources :ad_hoc_reports, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :run_start
      get :run_progress
      get :run_results
      get :results
      get :export_csv
    end
  end

  # Thesauri
  namespace :thesauri do
    resources :managed_concepts, only: [:index, :show, :edit, :update, :create, :destroy] do
      collection do
        get :history
        get :set_with_indicators
      end
      member do
        get :edit_extension
        get :edit_subset
        get :find_subsets
        get :children
        post :add_child
        post :add_children_synonyms
        post :create_extension
        post :create_subset
        get :show_data
        get :changes
        get :changes_data
        get :changes_report
        get :differences
        get :synonym_links
        get :preferred_term_links
        get :change_instruction_links
        post :extensions, action: :add_extensions
        # delete :extensions, action: :destroy_extensions
        get :is_extended
        get :is_extension
        get :export_csv
        get :changes_summary
        get :changes_summary_data
        get :changes_summary_data_impact
        get :impact
        get :differences_summary
        patch :update_properties
        get :upgrade_data
        put :upgrade
        post :add_rank
        delete :remove_rank
        put :update_rank
        get :get_ranked_children
      end
    end
    resources :unmanaged_concepts, only: [:show, :edit, :update, :destroy] do
      member do
        get :show_data
        get :changes
        get :changes_data
        get :differences
        get :synonym_links
        get :preferred_term_links
        get :change_instruction_links
        patch :update_properties
      end
    end
    resources :subsets, only: [] do
      member do
        post :add
        delete :remove
        delete :remove_all
        put :move_after
        get :list_children
      end
    end
  end

  resources :thesauri, only: [:index, :show, :create, :edit, :destroy] do
    collection do
      get :index_owned
      get :history
      post :extension
      get :search_current
      get :search_multiple
    end
    member do
      post :clone
      get :children
      get :children_with_indicators
      post :add_child
      get :changes
      get :changes_data
      get :changes_report
      get :changes_impact
      get :export_csv
      get :submission
      get :submission_data
      get :submission_report
      get :search
      get :export_csv
      post :add_subset
      get :release_select
      put :reference, action: :set_reference
      get :reference, action: :get_reference
      post :select_children
      put :deselect_children
      put :deselect_all_children
      put :change_child_version
      get :compare
      get :compare_data
      get :compare_csv
      get :upgrade
    end
  end

  # resources :thesaurus_concepts, :only => [:update, :show, :destroy, :edit] do
  #   collection do
  #     get :children
  #     post :add_child
  #   end
  #   member do
  #     get :cross_reference_start
  #     get :cross_reference_details
  #   end
  # end

  resources :uploads, :only => [:index, :create] do
    collection do
      delete :destroy_multiple
      delete :destroy_all
    end
  end

  # Imports
  namespace :imports do
    # resources :adam_models, :only => [:new, :create]
    # resources :adam_igs, :only => [:new, :create]
    resources :cdisc_terms, :only => [:new, :create]
    resources :change_instructions, :only => [:new, :create]
    resources :crfs, :only => [:new, :create] do
      collection do
        get :items
      end
    end
    resources :sponsor_term_format_two, :only => [:new, :create]
  end
  resources :imports, :only => [:index, :show, :destroy] do # Make sure this is after the namespace to avoid the :index/:show clash
    collection do
      get :list
      delete :destroy_multiple
    end
  end

  # Exports
  resources :exports, :only => [:index] do
    collection do
      get :terminologies
      get :biomedical_concepts
      get :forms
      get :start
      get :download
    end
  end

  # CDISC Terminology
  resources :cdisc_terms, :only => [:index] do
    collection do
      get :history
    end
    member do
    end
  end

  # BCs
  resources :biomedical_concept_templates do
    collection do
      get :history
      get :list
      get :all
    end
  end
  namespace :biomedical_concepts do
    resources :items
    resources :datatypes
    resources :properties do
      member do
        post 'term', to: 'properties#add', as: :add
        delete 'term', to: 'properties#remove', as: :remove
      end
    end
    resources :property_values
  end
  resources :biomedical_concepts do
    member do
      get :export_json
      get :export_ttl
      get :clone
      get :upgrade
      get :show_full
      get :edit_lock
    end
    collection do
      get :editable
      get :history
      post :clone_create
      get :list
      get :edit_multiple
    end
  end
  resources :forms do
    collection do
      get :history
      get :view
      get :placeholder_new
      post :placeholder_create
      get :acrf
      get :crf
      get :markdown
      get :clone
      post :clone_create
      get :branch
      post :branch_create
      get :export_json
      get :export_ttl
      get :export_odm
    end
  end
  namespace :forms do
    resources :groups
    resources :items, :only => [:show]
  end
  resources :backgrounds, :only => [:index, :destroy] do
    collection do
      delete :destroy_multiple
    end
  end
  resources :sdtm_models do
    collection do
      get :history
      get :import
      post :create
    end
    member do
      get :export_json
      get :export_ttl
    end
  end
  namespace :sdtm_models do
    resources :variables
  end

app/models/study.rb
class Study < IsoManagedV2

  configure rdf_type: "http://www.assero.co.uk/Protocol#Study",
            uri_suffix: "ST"

  data_property :description
  object_property :implements, cardinality: :one, model_class: "Protocol"

  def protocol
    implements_objects
  end

  def visits
    results = {}
    query_string = %Q{
      SELECT DISTINCT ?v ?vl ?vsn ?tp WHERE
      {
        #{self.uri.to_ref} pr:implements ?p .
        ?p pr:specifiesEpoch ?e .
        ?e pr:ordinal ?eo .
        ?e isoC:label ?el .
        ?e ^pr:inEpoch ?ele .         
        ?ele pr:containsTimepoint ?tp .
        ?tp pr:atOffset ?o .
        ?o pr:windowOffset ?os .
        ?tp pr:inVisit ?v .
        ?v isoC:label ?vl .
        ?v pr:shortName ?vsn .
      } ORDER BY ?os
    }
    query_results = Sparql::Query.new.query(query_string, "", [:isoC, :bo, :isoC, :pr])
    triples = query_results.by_object_set([:v, :vl, :vsn, :tp])
    return [] if triples.empty?
    triples.each do |entry|
      results[entry[:v].to_s] = {id: entry[:v].to_id, label: entry[:vl], short_name: entry[:vsn], timepoints: []} unless results.key?(entry[:v].to_s)
      results[entry[:v].to_s][:timepoints] << entry[:tp].to_id
    end
    results.map{|k,v| v}
  end

  def soa
    visit_set = visits
    visit_set.each {|h| h[:applies] = false}
    results = {}
    query_string = %Q{
      SELECT DISTINCT ?v ?vl ?x ?xl ?xt ?xi WHERE
      {
        #{self.uri.to_ref} pr:implements ?p .
        ?p pr:specifiesEpoch ?e .
        ?e pr:ordinal ?eo .
        ?e isoC:label ?el .
        ?e ^pr:inEpoch ?ele .         
        ?ele pr:containsTimepoint ?tp .
        ?tp pr:inVisit ?v .
        ?tp pr:atOffset ?o .
        ?o pr:windowOffset ?os .
        ?v isoC:label ?vl .
        ?tp pr:hasPlanned/pr:isDerivedFrom ?x .
        ?x isoC:label ?xl . 
        ?x isoT:hasIdentifier/isoI:identifier ?xi .  
        ?x rdf:type ?xt .
      } ORDER BY ?os
    }
    query_results = Sparql::Query.new.query(query_string, "", [:isoC, :bo, :isoC, :pr, :isoT, :isoI])
    triples = query_results.by_object_set([:v, :vl, :x, :xl, :xi, :xt])
    return [] if triples.empty?
    triples.each do |entry|
      uri_s = entry[:x].to_s
      dup_vs = Marshal.load(Marshal.dump(visit_set))
      results[uri_s] = {label: entry[:xl], identifier: entry[:xi], id: entry[:x].to_id, rdf_type: entry[:xt].to_s, uri: entry[:x].to_s, visits: dup_vs} if !results.key?(uri_s)
      next if entry[:v].blank?
      visit = results[uri_s][:visits].find{|x| x[:id] == entry[:v].to_id} 
      visit[:applies] = true
    end
    results.map{|k,v| v}
  end

end

app/models/study_form.rb
class StudyForm < IsoConceptV2

  configure rdf_type: "http://www.assero.co.uk/Protocol#StudyForm",
            base_uri: "http://#{ENV["url_authority"]}/STFRM",
            uri_unique: true

  object_property :is_derived_from, cardinality: :one, model_class: "Form"

end

app/controllers/studies_controller.rb
# Studies Controller

require 'controller_helpers.rb'

class StudiesController < ApplicationController

  include ControllerHelpers

  before_action :authenticate_user!

  C_CLASS_NAME = self.name

  def index
    authorize Form
    @protocols = Protocol.unique
  end

  def index_data
    authorize Form, :view?
    studies = Study.unique
    studies = studies.map{|x| x.reverse_merge!({history_path: history_studies_path({study:{identifier: x[:identifier], scope_id: x[:scope_id]}})})}
    render json: {data: studies}, status: 200
  end

  # def update

  # end

  def create
    authorize Form, :create?
    params = the_params.slice(:identifier, :label, :description)
    protocol = Protocol.latest(identifier: the_params[:protocol_identifier], scope: IsoRegistrationAuthority.repository_scope)
    params[:implements] = protocol.uri
    study = Study.create(params)
    if study.errors.empty?
      render json: {history_url: history_studies_path({study:{identifier: study.scoped_identifier, scope_id: study.has_identifier.has_scope.id}})}, status: 200
    else
      render json: {errors: [study.errors.full_messages]}, status: 422
    end
  end

  def history
    authorize Form, :show?
    @study = Study.latest(identifier: the_params[:identifier], scope: IsoNamespace.find(the_params[:scope_id]))
    @identifier = the_params[:identifier]
    @scope_id = the_params[:scope_id]
    @close_path = studies_path
  end

  def history_data
    authorize Form, :show?
    results = []
    history_results = Study.history_pagination(identifier: the_params[:identifier], scope: IsoNamespace.find(the_params[:scope_id]), count: the_params[:count], offset: the_params[:offset])
    current = Study.current_uri(identifier: the_params[:identifier], scope: IsoNamespace.find(the_params[:scope_id]))
    latest = Study.latest_uri(identifier: the_params[:identifier], scope: IsoNamespace.find(the_params[:scope_id]))
    results = add_history_paths(Form, history_results, current, latest)
    render json: {data: results, offset: the_params[:offset].to_i, count: results.count}
  end

  def build
    authorize Form, :edit?
    @study = Study.find_with_properties(protect_from_bad_id(params))
    @study_empty = @study.protocol.design.empty?
    @close_path = history_studies_path({study: {identifier: @study.scoped_identifier, scope_id: @study.scope}})
  end

  def design
    authorize Form, :edit?
    study = Study.find_minimum(protect_from_bad_id(params))
    render json: {data: study.protocol.design}
  end

  def soa
    authorize Form, :show?
    study = Study.find_minimum(protect_from_bad_id(params))
    render json: {data: study.soa}
  end

  def visits
    authorize Form, :show?
    study = Study.find_minimum(protect_from_bad_id(params))
    render json: {data: study.visits}
  end

private

  def the_params
    params.require(:study).permit(:identifier, :label, :description, :protocol_identifier, :scope_id, :count, :offset)
  end

  # Path for given action
  def path_for(action, object)
    case action
      when :show
        return ""
      when :edit
        return ""
      when :build
        return build_study_path(object)
      else
        return ""
    end
  end

end

app/views/studies/build.html.erb
<%= javascript_tag 'setPageTitle("Study build: '+@study.has_identifier.identifier+' ('+@study.semantic_version+')")' %>

<%= javascript_include_tag "studies/build" %>
<%= javascript_tag "var studyEmpty = #{@study_empty};" %>
<% third_level_breadcrumb(:studies, @study, @close_path) %>


<div class="row">
  <%= render layout: "shared/studies/study_header", :locals => {:item => @study, :badge => "icon-study"} do %>
    <div class="actions-wrap">

      <%= render partial: "shared/buttons/ico_btn_secondary", :locals => {link_path: "#", id: "timeout",
        icon: "icon-lock", btn_text: "", dt_toggle: "", disabled: false } %>
      <%= render partial: "shared/buttons/ico_btn_secondary", :locals => {link_path: @close_path, id: "close",
        icon: "icon-long-arrow", btn_text: "Return", dt_toggle: "", disabled: false } %>

    </div>
  <% end %>
</div>

<div class="row">
	<div class="col-md-12 card wide">
    <div class="card-header">
      Study Build
    </div>
    <div class="card-content">
      <%= render partial: "shared/studies/study_build_panel" %>
  	</div>
	</div>
</div>

<%= render partial: "shared/items_selector/items_selector_modal", :locals => {id: "1"} %>
<%= render partial: "shared/items_selector/items_selector_modal", :locals => {id: "2", with_refs: false} %>
<%= render partial: "shared/studies/new_timepoint_modal" %>

app/views/studies/history.html.erb
<%= javascript_tag 'setPageTitle("History: '+@identifier+'")' %>

<%= javascript_include_tag 'shared/iso_managed/history_page' %>
<%= javascript_tag "var history_data_path = '#{history_data_studies_path}',
 												url_rs_path = '#{iso_registration_states_v2_path("rs_id")}',
												strict_params = 'study',
												identifier = '#{@identifier}',
												scope_id = '#{@scope_id}';" %>

<% second_level_breadcrumb(:studies, @scope_id, @identifier) %>

<div class="row">
  <%= render layout: "shared/thesauri/simple_header_card", :locals => {badge: "icon-study", item: @study, header_title: "Item History", with_tags: false} do %>
    <div class="actions-wrap">
			<%= render partial: "shared/buttons/ico_btn_secondary", :locals => {link_path: @close_path, id: "close",
				icon: "icon-long-arrow", btn_text: "Return", dt_toggle: "", disabled: false } %>
    </div>
	<% end %>
</div>

<div class="row centered">
	<div class="col-md-11 card table-cardstyle">
		<%= render partial: "shared/history_panel", locals: {title: "Version History of '#{@identifier}'"} %>
	</div>
</div>

app/views/studies/index.html.erb
<%= javascript_tag 'setPageTitle("Index: Studies")' %>

<%= javascript_tag "var indexUrl = '#{index_data_studies_path}',
                        strict_param = 'study',
                        count = -1;" %>

<%= javascript_include_tag 'shared/iso_managed/index_page', 'shared/index_panel' %>
<%= stylesheet_link_tag 'shared/datatables_loading' %>

<% first_level_breadcrumb (:studies) %>

<div class="row">
  <%= render partial: "shared/simple_header_tiny", :locals => {badge: "icon-study",
    main_text: "Studies",
    sub_text: "Browse all Studies in the system." } %>
</div>

<div class="row">
	<div class="col-md-12 card wide">
      <div class="card-header">Index</div>
    <div class="card-content table-cardstyle">
			<div class="half-blocks-wrap">
				<div class="font-light half-block">
					Below is the list of all <span class="text-link font-regular">sponsor</span> Studies.
					Use the Search bar to find the Study you are looking for. To see its respective History page, click on 'History'.
				</div>
				<div class="actions-wrap half-block">
					<% if policy(Thesaurus::ManagedConcept).new? %>
          <a href="#new-study-modal" class="btn medium green" id="new-study-button" data-toggle="modal">
            <span class="icon-plus text-tiny"></span>&nbsp;
            New Study
          </a>
					<% end %>
				</div>
			</div>
			<hr>
			<div class="table-width-wrapper">
	      <table id="index" class="table table-striped table-bordered table-condensed">
	        <thead>
	          <tr>
	            <th class="th-xsmall fit">Owner</th>
							<th class="th-medium fit">Identifier</th>
							<th>Label</th>
							<th class="fit"></th>
	          </tr>
	        </thead>
	        <tbody>
	        </tbody>
	      </table>
			</div>
		</div>
  </div>
  <%= render partial: "shared/studies/new_study_modal" %>
</div>