config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}#, :path_names => { :sign_in => "login", :sign_out => "logout" }
  resources :users, except: :create do
    member do
      put :update_name
      put :lock
      put :unlock
    end
    collection do
     get :stats_by_domain
    #   get :stats_by_year
    #   get :stats_by_current_week
    #   get :stats_by_year_by_month
    #   get :stats_by_year_by_week
    end
  end
  post 'create_user' => 'users#create', as: :create_user
  resources :user_settings

  match 'api(/:id)' => 'api#options', via: [:options]
  resources :api do
    collection do
      get :discover
      get :list
      get :form
      get :form_annotations
      get :domain
      get :thesaurus_concept
      get :bc_property
    end
  end
  namespace :api do
    namespace :v2 do
      resources :thesauri, only: [:show]
      resources :thesaurus_concepts, only: [:index, :show] do
        member do
          get :parent
          get :child
        end
      end
      resources :iso_managed, only: [:index]
      resources :biomedical_concepts, only: [] do
        member do
          get :domains
        end
      end
      resources :sdtm_user_domains, only: [:show]
      resources :sdtm_ig_domains, only: [:show] do
        member do
          get :clones
        end
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
  resources :iso_namespaces, only: [:index, :new, :create, :destroy]
  resources :iso_registration_authorities, only: [:index, :new, :create, :destroy]
  resources :iso_scoped_identifiers, only: [:update]
  resources :iso_scoped_identifiers_v2, only: [:update]
  resources :iso_registration_states, only: [:update] do
    collection do
      get :current
    end
  end
  resources :iso_concept, only: [:show] do
    collection do
      get :graph
      get :graph_links
      get :impact
      get :impact_start
      get :impact_next
      get :changes
    end
    member do
      get :tags
      put :add_tag
      put :remove_tag
      get :edit_tags
      get :tags_full
      get :change_notes
      get :change_instructions
      get :indicators
      post :change_note, action: :add_change_note
    end
  end
  namespace :annotations do
    resources :change_notes, only: [:update, :destroy]
    resources :change_instructions, only: [:create, :edit, :update, :destroy] do
      member do
        get :show
        put :add_references
        put :remove_reference
      end
    end
  end
  resources :iso_managed do
    collection do
      get :status
      get :find_by_tag
      get :tags
      get :graph
      get :graph_links
      get :impact
      get :impact_start
      get :impact_next
      get :changes
      get :comments
    end
    member do
      get :branches
      get :export
    end
  end
  resources :iso_managed_v2, only: [] do
    member do
      get :status
      get :impact
      get :make_current
      post :update_status
      put :update_semantic_version
      get :list_change_notes
      get :list_change_notes_data
      get :export_change_notes_csv
    end
    collection do
      get :find_by_tag
    end
  end
  resources :iso_registration_states_v2, only: [] do
    member do
      put :update
    end
  end
  resources :dashboard, only: [:index] do
    collection do
      get :view
      get :database
      get :admin
    end
  end
  resources :iso_concept_systems, only: [:index, :show, :destroy] do
    member do
      post :add
    end
  end
  namespace :iso_concept_systems do
    resources :nodes, only: [:destroy, :update] do
      member do
        post :add
      end
    end
  end
  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
      get :stats_by_domain
      get :stats_by_year
      get :stats_by_current_week
      get :stats_by_year_by_month
      get :stats_by_year_by_week
    end
  end
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end
  resources :ad_hoc_reports, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :run_start
      get :run_progress
      get :run_results
      get :results
      get :export_csv
    end
  end

  # Thesauri
  namespace :thesauri do
    resources :managed_concepts, only: [:index, :show, :edit, :update, :create, :destroy] do
      collection do
        get :history
        get :set_with_indicators
      end
      member do
        get :edit_extension
        get :edit_subset
        get :find_subsets
        get :children
        post :add_child
        post :add_children_synonyms
        post :create_extension
        post :create_subset
        get :show_data
        get :changes
        get :changes_data
        get :changes_report
        get :differences
        get :synonym_links
        get :preferred_term_links
        get :change_instruction_links
        post :extensions, action: :add_extensions
        # delete :extensions, action: :destroy_extensions
        get :is_extended
        get :is_extension
        get :export_csv
        get :changes_summary
        get :changes_summary_data
        get :changes_summary_data_impact
        get :impact
        get :differences_summary
        patch :update_properties
        get :upgrade_data
        put :upgrade
        post :add_rank
        delete :remove_rank
        put :update_rank
        get :get_ranked_children
      end
    end
    resources :unmanaged_concepts, only: [:show, :edit, :update, :destroy] do
      member do
        get :show_data
        get :changes
        get :changes_data
        get :differences
        get :synonym_links
        get :preferred_term_links
        get :change_instruction_links
        patch :update_properties
      end
    end
    resources :subsets, only: [] do
      member do
        post :add
        delete :remove
        delete :remove_all
        put :move_after
        get :list_children
      end
    end
  end

  resources :thesauri, only: [:index, :show, :create, :edit, :destroy] do
    collection do
      get :index_owned
      get :history
      post :extension
      get :search_current
      get :search_multiple
    end
    member do
      post :clone
      get :children
      get :children_with_indicators
      post :add_child
      get :changes
      get :changes_data
      get :changes_report
      get :changes_impact
      get :export_csv
      get :submission
      get :submission_data
      get :submission_report
      get :search
      get :export_csv
      post :add_subset
      get :release_select
      put :reference, action: :set_reference
      get :reference, action: :get_reference
      post :select_children
      put :deselect_children
      put :deselect_all_children
      put :change_child_version
      get :compare
      get :compare_data
      get :compare_csv
      get :upgrade
    end
  end

  # resources :thesaurus_concepts, :only => [:update, :show, :destroy, :edit] do
  #   collection do
  #     get :children
  #     post :add_child
  #   end
  #   member do
  #     get :cross_reference_start
  #     get :cross_reference_details
  #   end
  # end

  resources :uploads, :only => [:index, :create] do
    collection do
      delete :destroy_multiple
      delete :destroy_all
    end
  end

  # Imports
  namespace :imports do
    # resources :adam_models, :only => [:new, :create]
    # resources :adam_igs, :only => [:new, :create]
    resources :cdisc_terms, :only => [:new, :create]
    resources :change_instructions, :only => [:new, :create]
    resources :crfs, :only => [:new, :create] do
      collection do
        get :items
      end
    end
    resources :sponsor_term_format_two, :only => [:new, :create]
  end
  resources :imports, :only => [:index, :show, :destroy] do # Make sure this is after the namespace to avoid the :index/:show clash
    collection do
      get :list
      delete :destroy_multiple
    end
  end

  # Exports
  resources :exports, :only => [:index] do
    collection do
      get :terminologies
      get :biomedical_concepts
      get :forms
      get :start
      get :download
    end
  end

  # CDISC Terminology
  resources :cdisc_terms, :only => [:index] do
    collection do
      get :history
    end
    member do
    end
  end

  # BCs
  resources :biomedical_concept_templates do
    collection do
      get :history
      get :list
      get :all
    end
  end
  namespace :biomedical_concepts do
    resources :items
    resources :datatypes
    resources :properties do
      member do
        post 'term', to: 'properties#add', as: :add
        delete 'term', to: 'properties#remove', as: :remove
      end
    end
    resources :property_values
  end
  resources :biomedical_concepts do
    member do
      get :export_json
      get :export_ttl
      get :clone
      get :upgrade
      get :show_full
      get :edit_lock
    end
    collection do
      get :editable
      get :history
      post :clone_create
      get :list
      get :edit_multiple
    end
  end
  resources :forms do
    collection do
      get :history
      get :view
      get :placeholder_new
      post :placeholder_create
      get :acrf
      get :crf
      get :markdown
      get :clone
      post :clone_create
      get :branch
      post :branch_create
      get :export_json
      get :export_ttl
      get :export_odm
    end
  end
  namespace :forms do
    resources :groups
    resources :items, :only => [:show]
  end
  resources :backgrounds, :only => [:index, :destroy] do
    collection do
      delete :destroy_multiple
    end
  end
  resources :sdtm_models do
    collection do
      get :history
      get :import
      post :create
    end
    member do
      get :export_json
      get :export_ttl
    end
  end
  namespace :sdtm_models do
    resources :variables
  end

app/controllers/sdtm_models_controller.rb
class SdtmModelsController < ApplicationController
  
  before_action :authenticate_user!
  
  C_CLASS_NAME = "SdtmModelsController"
  
  def history
    authorize SdtmModel
    @history = SdtmModel.history()
  end
  
  def import
    authorize SdtmModel
    @files = Dir.glob(Rails.root.join("public","upload") + "*.xlsx")
    @sdtm_class_model = SdtmModel.new
    @next_version = SdtmModel.all.last.next_version
  end
  
  def create
    authorize SdtmModel, :import?
    hash = SdtmModel.create(the_params)
    @sdtm_model = hash[:object]
    @job = hash[:job]
    if @sdtm_model.errors.empty?
      redirect_to backgrounds_path
    else
      flash[:error] = @sdtm_model.errors.full_messages.to_sentence
      redirect_to history_sdtm_models_path
    end
  end
  
  def show
    authorize SdtmModel
    @sdtm_model_classes = Array.new
    @sdtm_model = SdtmModel.find(params[:id], the_params[:namespace])
    @sdtm_model.class_refs.each do |class_ref|
      @sdtm_model_classes << IsoManaged.find(class_ref.subject_ref.id, class_ref.subject_ref.namespace, false)
    end
  end

  def export_ttl
    authorize SdtmModel
    @sdtm_model = IsoManaged::find(params[:id], the_params[:namespace])
    send_data to_turtle(@sdtm_model.triples), filename: "#{@sdtm_model.owner_short_name}_#{@sdtm_model.identifier}.ttl", type: 'application/x-turtle', 
    	disposition: 'inline'
  end
  
  def export_json
    authorize SdtmModel
    @sdtm_model = IsoManaged::find(params[:id], the_params[:namespace])
    send_data @sdtm_model.to_json.to_json, filename: "#{@sdtm_model.owner_short_name}_#{@sdtm_model.identifier}.json", :type => 'application/json; header=present', 
    	disposition: "attachment"
  end

private
  
  def the_params
    params.require(:sdtm_model).permit(:namespace, :version, :version_label, :date, :files => [] )
  end  

end

app/views/sdtm_models/history.html.erb
<%= javascript_include_tag 'standard_datatable' %>
<% first_level_breadcrumb (id_to_type('sdtm_models')) %>
<h3>History: CDISC SDTM Model</h3>
<div class="col-md-12">
	<table id="main" class="table table-striped table-bordered table-condensed">
		<%= render partial: "shared/stdInstanceHeader" %>
		<tbody>
			<% current_item = get_current_item(@history) %>
			<%  @history.each do |item| %>
				<%= render partial: "shared/stdInstanceRow", :locals => {:item => item, 
	  				:current_item => current_item, 
	  				:showPath => sdtm_model_path(:id => item.id, :sdtm_model => { :namespace => item.namespace }), 
	  				:searchPath => "", 
	  				:viewPath => "",
	  				:editPath => "",
	  				:deletePath => "",
	  				:index_label => "",
	  				:index_path => "",
	  				:mi_class => SdtmModel } %>
			<% end %>				
		</tbody>
	</table>
	<%= link_to "Import", import_sdtm_models_path, id: "import_button", :class => "btn btn-success" %>
</div>

app/views/sdtm_models/import.html.erb
<h3>Import CDISC SDTM Model Version</h3>
<div class="col-md-6">
  <%= form_for @sdtm_class_model, url: sdtm_models_path do |f| %>
      <div class="form-group">
          <%= label_tag :version, "Version:" %><br/>
          <%= text_field_tag "sdtm_model[version]", "#{@next_version}", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :version_label, "Version Label:" %><br/>
        <%= text_field_tag "sdtm_model[version_label]", "", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :date, "Model Release Date:" %><br/>
        <%= date_field_tag "sdtm_model[date]", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :files, "File:" %><br/>
        <%= select_tag("sdtm_model[files][]", options_for_select(@files), class: "form-control", :multiple => true) %>
      </div>
      <br/>
      <%= f.submit "Create", class: "btn  " %>
      <%= link_to "Close", history_sdtm_models_path, :class => "btn " %>
  <% end %>
</div>

app/views/sdtm_models/import_file.html.erb
<h3>Import CDISC SDTM Model Version</h3>
<div class="col-md-6">
  <%= form_for @sdtm_class_model, url: import_sdtm_models_path do |f| %>
      <div class="form-group">
          <%= label_tag :version, "Version (internal system):" %><br/>
          <%= text_field_tag "sdtm_model[version]", "", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :version_label, "Version label:" %><br/>
        <%= text_field_tag "sdtm_model[version_label]", "", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :date, "Model release date:" %><br/>
        <%= date_field_tag "sdtm_model[date]", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :files, "File:" %><br/>
        <%= select_tag("sdtm_model[files][]", options_for_select(@files), class: "form-control", :multiple => true) %>
      </div>
      <br/>
      <%= f.submit "Create", class: "btn btn-default btn-primary" %>
  <% end %>
</div>

app/views/sdtm_models/show.html.erb
<%= javascript_include_tag 'standard_datatable' %>
<% second_level_breadcrumb("CDISC SDTM Models", history_sdtm_models_path, "V#{@sdtm_model.semantic_version}") %>
<%= render partial: "shared/stdInstanceTitle", :locals => {:title => "Show:", :item => @sdtm_model} %>
<div class="col-md-12">
	<h4>Details</h4>
	<table class="table table-striped table-bordered table-condensed">
		<thead>
	  		<tr>
	    		<th>Identifer</th>
	    		<th>Label</th>
	    		<th>Owner</th>
	    		<th>Version</th>
	    		<th>Version Label</th>
	  		</tr>
		</thead>
		<tbody>
	  		<tr>
	    		<td><%= @sdtm_model.identifier %></td>
			    <td><%= @sdtm_model.label %></td>
			    <td><%= @sdtm_model.owner %></td>
			    <td><%= @sdtm_model.semantic_version %></td>
			    <td><%= @sdtm_model.versionLabel %></td>
	  		</tr>
		</tbody>
	</table>
	<h4>Variables</h4>
	<table id="main" class="table table-striped table-bordered table-condensed">
	  	<thead>
			<tr>
		  		<th>Role (Classification)</th>
		    	<th>Sub Classification</th>
		    	<th>Ordinal</th>
		    	<th>Variable Name</th>
		    	<th>Variable Label</th>
		    	<th>Type</th>
		    	<th>Desciption</th>
		  	</tr>
		</thead>
		<tbody>
			<% @sdtm_model.children.each do |item| %>
		  	<tr>
		    	<td><%= item.classification_label %></td>
		    	<td><%= item.sub_classification_label %></td>
		    	<td><%= item.ordinal %></td>
		    	<td><%= item.name %></td>
		    	<td><%= item.label %></td>
		    	<td><%= item.datatype_label %></td>
		    	<td><%= item.description %></td>
		  	</tr>
			<% end %>
		</tbody>
	</table>
	<h4>Model Classes</h4>
	<table id="secondary" class="table table-striped table-bordered table-condensed">
	  	<thead>
	  		<tr>
	    		<th>Identifer</th>
	    		<th>Label</th>
	    		<th>Owner</th>
	    		<th>Version</th>
	    		<th>Version Label</th>
	    		<th></th>
	  		</tr>
		</thead>
		<tbody>
	  	<% @sdtm_model_classes.each do |item| %>
		  	<tr>
	    		<td><%= item.identifier %></td>
			    <td><%= item.label %></td>
			    <td><%= item.owner %></td>
			    <td><%= item.semantic_version %></td>
			    <td><%= item.versionLabel %></td>
	    		<td><%= link_to "Show", sdtm_model_domain_path(:id => item.id, :sdtm_model_domain => { :namespace => item.namespace }), :class => "btn  btn-xs" %></td>
	  		</tr>
	  		<% end %>
		</tbody>
	</table>
	<%= link_to "Export JSON", export_json_sdtm_model_path(:id => @sdtm_model.id, sdtm_model: { :namespace => @sdtm_model.namespace }), :class => "btn btn-info" %>
	<%= link_to "Export Turtle", export_ttl_sdtm_model_path(:id => @sdtm_model.id, sdtm_model: { :namespace => @sdtm_model.namespace }), :class => "btn btn-info" %>
	<br/><br/>
</div>